### ISSUE TITLE
Required modifier should appear before access modifiers (In Visual Studio Community 2022)

### ISSUE THREAD

**Issue by ayanesuarome** [markjprice/apps-services-net7#10]
**Chapter:** 1
**Page Number:** 36
**Section Title:** Requiring properties to be set during instantiation
**Problem to fix:** The 'required' modifier should appear before access modifier 'public'
**Suggested solution:** required public string ISBN { get; set; }
**IDE:** Microsoft Visual Studio Community 2022 (2) (64-bit)

**Comment by markjprice** [comment]
The official Microsoft documentation for the `required` keyword puts it *after* an access modifier like `public`, as shown at the following link:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required

**Comment by ayanesuarome** [comment]
Yes you are right. Weird, it maight be because of the code smells.
Thanks!
