### ISSUE TITLE
Chapter 17, Page 613, Bullet 10, _Imports.cshtml

### ISSUE THREAD

**Issue by BobMolloy** [markjprice/apps-services-net7#11]
Should be _Imports.razor.

**Comment by markjprice** [comment]
Thanks. I also got it wrong on page 600. I have created some more items for this:

https://github.com/markjprice/apps-services-net7/blob/main/docs/errata/errata.md#page-600---building-a-local-storage-service

https://github.com/markjprice/apps-services-net7/blob/main/docs/errata/errata.md#page-613---exploring-radzen-blazor-components
