### ISSUE TITLE
Missing using statement

### ISSUE THREAD

**Issue by mdevol58** [markjprice/apps-services-net7#18]
Please check that your issue is not already in the [errata aka list of corrections and improvements](https://github.com/markjprice/apps-service-net7/blob/main/docs/errata/README.md). Please note that PRs will be ignored because code in the repo must match the print book already published. Please raise an issue instead so I can handle it appropriately. All issues will be entered into the errata once closed and fixed in the next book edition.

Chapter:  11
Page Number:  411
Section Title:  Using an ASP.NET Core MVC project as a GraphQL client
Problem to fix: In step 12 you say "... import the namespace for working with text encoding and for our Northwind entity models ..."; however, the using statement for Northwind is missing
Suggested solution: add the following statement -  using Northwind.Mvc.GraphQLClient.Models;
Other useful information e.g. OS, coding tools, and so on:

**Comment by markjprice** [comment]
Thanks! I've added this to the errata: https://github.com/markjprice/apps-services-net7/blob/main/docs/errata/errata.md#page-411---using-an-aspnet-core-mvc-project-as-a-graphql-client
