### ISSUE TITLE
Incorrect HTML element closing

### ISSUE THREAD

**Issue by mdevol58** [markjprice/apps-services-net7#19]
Please check that your issue is not already in the [errata aka list of corrections and improvements](https://github.com/markjprice/apps-service-net7/blob/main/docs/errata/README.md). Please note that PRs will be ignored because code in the repo must match the print book already published. Please raise an issue instead so I can handle it appropriately. All issues will be entered into the errata once closed and fixed in the next book edition.

Chapter: 16
Page Number: 578
Section Title: Building Blazor Components
Problem to fix: On step 17 the added markup elements closing is incorrect, should be /> instead of >. Minor thing as the IDE automatically makes the correction.
Suggested solution: Correct the markup to use /> instead of >
Other useful information e.g. OS, coding tools, and so on:

**Comment by markjprice** [comment]
Thanks! I've added an errata item for this: https://github.com/markjprice/apps-services-net7/blob/main/docs/errata/errata.md#page-578---building-blazor-components
