### ISSUE TITLE
StrawberryShake - access to obj\\berry is denied - fix included

### ISSUE THREAD

**Issue by sjharper79** [markjprice/apps-services-net7#25]
Please check that your issue is not already in the [errata aka list of corrections and improvements](https://github.com/markjprice/apps-service-net7/blob/main/docs/errata/README.md). Please note that PRs will be ignored because code in the repo must match the print book already published. Please raise an issue instead so I can handle it appropriately. All issues will be entered into the errata once closed and fixed in the next book edition.

Chapter: 11
Page Number: 419
Section Title: Understanding Strawberry Shake
Problem to fix: When using VS2022 and StrawberryShake 12, compilation fails. Error message is "SS0006 Access to the path 'obj\\berry' is denied." When building from the command line using dotnet build, the error message is "error SS0006: Method not found: 'Void StrawberryShake.CodeGeneration.CSharp.CSharpGeneratorSettings.set_RequestStrategy(StrawberryShake.Tools.Configuration.RequestStrategy)'"
Suggested solution: Add <StrawberryShake_State>$(MSBuildProjectExtensionsPath)berry</StrawberryShake_State> to a PropertyGroup for the project. Solution listed here: https://stackoverflow.com/questions/75693518/c-sharp-net-build-error-due-to-strawberry-shake-graphql-client-error-access.
Other useful information e.g. OS, coding tools, and so on:

**Comment by markjprice** [comment]
Thank you, Stephen. I have added an errata item for this here:
https://github.com/markjprice/apps-services-net7/blob/main/docs/errata/errata.md#page-419---understanding-strawberry-shake---creating-a-console-app-client
