### ISSUE TITLE
English language in France ranked at 0.8

### ISSUE THREAD

**Issue by sjharper79** [markjprice/apps-services-net7#26]
Please check that your issue is not already in the [errata aka list of corrections and improvements](https://github.com/markjprice/apps-service-net7/blob/main/docs/errata/README.md). Please note that PRs will be ignored because code in the repo must match the print book already published. Please raise an issue instead so I can handle it appropriately. All issues will be entered into the errata once closed and fixed in the next book edition.

Chapter: 15
Page Number: 550
Section Title: Understanding the Accept-Language header
Problem to fix: In the third bullet after the paragraph explaining the Accept-Language syntax, it states:
* fr-FR;q=0.8: English language in France ranked at 0.8.
Suggested solution: It should say French, not English as shown below.
* fr-FR;q=0.8: French language in France ranked at 0.8.
Other useful information e.g. OS, coding tools, and so on:

**Comment by markjprice** [comment]
Thanks! This has been added to the errata:
https://github.com/markjprice/apps-services-net7/blob/main/docs/errata/errata.md#page-550---understanding-the-accept-language-header
