### ISSUE TITLE
Comparing HTML Helpers and Tag Helpers

### ISSUE THREAD

**Issue by sjharper79** [markjprice/apps-services-net7#27]
Chapter: **15**
Page Number: **550**
Section Title: **Comparing HTML Helpers and Tag Helpers**
Problem to fix: At the bottom of the page the statement says that all three examples generate an HTML element that looks like `<a href="/home/privacy">View our privacy policy.</a>` but they don't. Instead the first and last examples (I didn't do the middle one since it's the same as the first but has named parameters) generate the following HTML.

```
<a href="/Index/Privacy">View our privacy policy with an HTML Helper.</a>

<a href="/Home/Privacy">View our privacy policy with a Tag Helper.</a>
```

Suggested solution: **Update the HTML Helpers lines to use Home instead of Index.**

Other useful information e.g. OS, coding tools, and so on:
**When browsing to the /Index/Privacy link, error 404 is displayed. When browsing to the /home/privacy link, the private page is displayed.**

**Comment by markjprice** [comment]
Thanks! This has been added to the errata for 7th edition:
https://github.com/markjprice/apps-services-net7/blob/main/docs/errata/errata.md#page-550---comparing-html-helpers-and-tag-helpers

And the 8th edition:
https://github.com/markjprice/apps-services-net8/blob/main/docs/errata/errata.md#page-644---comparing-html-helpers-and-tag-helpers
