### ISSUE TITLE
Making the component a routable page component - Missing namespace

### ISSUE THREAD

**Issue by sjharper79** [markjprice/apps-services-net7#28]
Chapter: 16
Page Number: 590
Section Title: Making the component a routable page component
Problem to fix: In Step 3, the instructions state to add 

`<NavMenu />` 

to the MainLayout.razor file. When doing this, VS22 automatically autocompletes it to 

`<Northwind.BlazorWasm.Client.Pages.NavMenu />`. 

This is because the NavMenu.razor file doesn't specify a namespace and the MainLayout.razor file doesn't import a namespace that the NavMenu.razor file should be using. 

Suggested solution: 
In step 4, add a line to include 

`@using Packt.Shared`

at the top of the page.

In step 5, include a step to add 

`namespace Packt.Shared`

at the top of the file.

**Comment by sjharper79** [comment]
Revoke the suggestion for adding @using Packt.Shared to the top of the MainLayout.razor file since it is in the _Imports.razor file. The namespace should still be added to the NavMenu.razor file.

**Comment by markjprice** [comment]
By default, the `_Imports.razor` file created by the project template contains that following statement:
```cs
@using Northwind.BlazorWasm.Client.Components
```

This will import all components defined in the `Components` folder. None of the components need to be explicitly defined within that namespace if they are in the `Components` folder. For example, `Alert.razor`, `DialogBox.razor`, `NavMenu.razor` and `ProgressBar.razor` are all in that folder, none explicitly define their namespace, but all can be used in other components.

**Comment by sjharper79** [comment]
Oh yeah, I see what the problem I was having is. I put the NavMenu.razor file in the Pages folder instead of the Components folder. Upon moving it and removing all the namespace stuff, it works. 

Sorry for the mixup.
