### ISSUE TITLE
Page 72 - Bullet 2: Stored Procedures menu item location

### ISSUE THREAD

**Issue by BobMolloy** [markjprice/apps-services-net7#3]
This paragraph:

In your preferred database tool, add a new stored procedure. For example, if you are using
SQL Server Management Studio, then right-click Stored Procedures and select Add New Stored
Procedure.

Might be better as:

In your preferred database tool, add a new stored procedure. For example, if you are using
SQL Server Management Studio, **expand the Programmability node**, then right-click Stored Procedures and select Add New Stored
Procedure.

**Comment by markjprice** [comment]
Thank you, Bob, you're right. I've added this to the list of improvements:
https://github.com/markjprice/apps-services-net7/blob/main/docs/errata/improvements.md#page-72---executing-stored-procedures-using-adonet
