### ISSUE TITLE
Chapter 2, Page 88 - Connection String

### ISSUE THREAD

**Issue by BobMolloy** [markjprice/apps-services-net7#6]
The book says I should see this string:

Data Source=.;Initial Catalog=Northwind;Integrated
Security=True;Multiple Active Result Sets=True;Connect
Timeout=10;Encrypt=True;Trust Server Certificate=True

What I actually see is this:

Data Source=.;Initial Catalog=Northwind;Integrated Security=true;TrustServerCertificate=true;

**Comment by markjprice** [comment]
The book says "Your connection string will be different."

![image](https://user-images.githubusercontent.com/14040265/210218194-b1da7334-813e-4dfd-93e1-20c8c43f1d5d.png)
