### ISSUE TITLE
Chapter 6, Page 232, Bullet 3 - No Obsolete! Message

### ISSUE THREAD

**Issue by BobMolloy** [markjprice/apps-services-net7#8]
**ID10T error. Missed adding {3} to the WritleLine for obsolete.**

Chapter: 6
Page Number: 232
Section Title: 3
Problem to fix: Obsolete message not displaying 
Suggested solution:
Other useful information e.g. OS, coding tools, and so on:
Type: Packt.Shared.Animal
Method: Speak (Animal)
-> Modified by Johnni Rasmussen on 9/13/2022
-> Modified by Mark Price on 8/22/2022
Method: SpeakBetter (Animal)
Method: GetType (Object)
Method: ToString (Object)
Method: Equals (Object)
Method: GetHashCode (Object)
Constructor: .ctor (Animal)

**Comment by markjprice** [comment]
Here's my output:
![image](https://user-images.githubusercontent.com/14040265/212887503-ff8a6eb9-73ba-4dd6-8a17-8c4474b75943.png)
Are you sure that you added the code in Step 2:
```cs
foreach (MemberInfo member in members)
{
  ObsoleteAttribute? obsolete =
   member.GetCustomAttribute<ObsoleteAttribute>();

  WriteLine("{0}: {1} ({2}) {3}",
    member.MemberType, member.Name,
    member.DeclaringType?.Name, 
    obsolete is null ? "" : $"Obsolete! {obsolete.Message}"); // <-- this is where it outputs extra text
```

**Comment by markjprice** [comment]
Ah! I've just seen your edit about missing {3}. In the next edition I will add a note to highlight that because I can imagine it's a common mistake.
